name: Docker Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Compose
        run: docker-compose build
      
      - name: Test Docker Compose
        run: |
          ENV=dev docker-compose up -d
          docker-compose ps
          docker-compose logs